### ISSUE TITLE
can we loosen the peerDependencies versions?

### ISSUE THREAD

**Issue by SylvanSign** [delucis/bgio-effects#113]
Hi, this looks like a very cool library! And thanks for your work on boardgame.io as well :)

I'm interested in trying this plugin alongside the latest versions of boardgame.io and React, but the peerDependencies are preventing that:
https://github.com/delucis/bgio-effects/blob/c6c868fb57f38a67dcc96905ded8a0eeee08d303/package.json#L72-L73

Is it possible to loosen these peerDependencies versions? Ie. do you know whether your plugin will work with latest boardgame.io (`0.43`) and latest react (`17`)?

Thanks!

**Comment by delucis** [comment]
Hi @SylvanSign — oh, right, I forgot that the `^` with versions less than 1.0.0 locks the minor version. To the best of my knowledge this should be compatible with `boardgame.io@>=0.39.16`. React 17 should also be supported. Would you like to open a PR changing those?

In a way it would also be nice to run tests for both React 16 & 17 and say `boardgame.io@0.39.16` and `boardgame.io@latest`, but not quite sure how to set that up.

**Comment by SylvanSign** [comment]
opened a PR but I'm not sure if it's exactly what you had in mind. I'm not super familiar with JS libraries

**Comment by delucis** [comment]
That’s ok! I left a review suggesting some changes.

**Comment by delucis** [comment]
Closed in #116
