### ISSUE TITLE
Vanilla JS examples

### ISSUE THREAD

**Issue by mattbrailsford** [delucis/bgio-effects#148]
Hey,

This looks like something I'm looking for being able to trigger an animation on all connected clients when a player makes a move, however I'm not using bgio in a React setup so was wondering if this library is usable in a VanillaJS setup, and if so, are there are code examples for effect handling?

**Comment by delucis** [comment]
@mattbrailsford Currently this package only provides the effect emitting/listening logic in a React component unfortunately. I have been meaning to try to separate out the core logic so it is useable with a vanilla JS client, but haven't had time. (In theory some of this code should actually be cleaner without React's lifecycle to worry about — we basically subscribe to the client, and set up the effect queue on every state update. A vanilla client adapter would offer its own `on` method to subscribe to specific effects.)

**Comment by mattbrailsford** [comment]
It would be super cool if it did, but I know the difficulties of maintaining libraries so understand finding the time is hard.

I tried looking though the react stuff to see if there was something usable, but it's all a bit beyond me 😂
