### ISSUE TITLE
(0 , non_secure_1.nanoid) is not a function

### ISSUE THREAD

**Issue by schirkan** [delucis/bgio-effects#362]
Hi, I tried to integrate this plugin into my bgio react game, but I get the following error:
```
Uncaught TypeError: (0 , non_secure_1.nanoid) is not a function
    at getData (plugin.js:11)
```

In your plugin.ts everythings looks fine:
```
const getData = (timeline: Timeline): Data => ({
  id: nanoid(8),
  duration: timeline.duration(),
  queue: timeline.getQueue(),
});
```
but the generated plugin.js in the npm package looks not correct:
```
const getData = (timeline) => ({
    id: (0, non_secure_1.nanoid)(8),
    duration: timeline.duration(),
    queue: timeline.getQueue(),
});
```

Searching for this error I found a simmilar issue:
https://github.com/ai/nanoid/issues/205

My core dependencies:
- react-scripts: 5.0.0
- react: 17.0.2
- bgio-effects: 0.5.0
- boardgame.io: 0.49.9

**Comment by schirkan** [comment]
In version 0.4.7 the code in plugin.js looks like this:
```
const getData = (timeline) => ({
    id: non_secure_1.nanoid(8),
    duration: timeline.duration(),
    queue: timeline.getQueue(),
});
```
Will try to downgrade until fixed.

**Comment by delucis** [comment]
Odd. Especially as the Create React App fix referenced in the issue you linked to, was released in CRA@5.0.0, which is what you’re using. I might try inlining a UUID generator as the requirements for this module are fairly minimal.

**Comment by delucis** [comment]
That said, the boardgame.io client itself uses the same import, so it may not fix anything, just duplicate code. Do you have a reproduction you can share? I’d like to reproduce this before trying to see how I might fix it.

**Comment by delucis** [comment]
Reproduced the bug with a basic CRA set up. Seeing if I can figure out a sensible workaround.

**Comment by delucis** [comment]
Downgrading `react-scripts` to 4.0.3 fixes this, so I guess it’s a regression in v5 (which was only recently released) that might get fixed. I’d suggest sticking with the downgraded `bgio-effects` for now (0.4.7 is more or less identical to 0.5.0) rather than downgrading CRA, and I’ll try to monitor if an upstream fix shows up.

**Comment by schirkan** [comment]
I also downgraded `react-scripts` and `bgio-effects` and the error is gone.

**Comment by delucis** [comment]
Release 0.5.1 removes the dependency on `nanoid`, so should fix this. Let me know if you still have issues!
