### ISSUE TITLE
Creating roll dice animation

### ISSUE THREAD

**Issue by artt** [delucis/bgio-effects#52]
Thanks a lot for this plugin! Seems like exactly what I need.

I'm wondering if I have a move called `roll` which would the fire the `rollEffect`, I'd like for the graphics to display a random number (between 1 and 6) 10 times, each with delay of 100ms. Then the final number is shown.

I set `updateStateAfterEffects` to `true`, and then in my effect listener I did:

```
export default function RolledDice({dice}) {

function sleep(ms) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

useEffectListener('roll', async () => {
	for (let i = 0; i < 10; i ++) {
		dice = random(1, 3)
		forceUpdate()
		await sleep(100)
	}
}, []);

return // some <div> with dice
```

I'm wondering if there's a better way to do this as I've read that `forceUpdate` [isn't a very good practice](https://stackoverflow.com/questions/53215285/how-can-i-force-component-to-re-render-with-hooks-in-react).

If there's an easy example on how to do this in the doc, that would be great. Thanks a lot!

**Comment by delucis** [comment]
Hi @artt — some more in-use examples would be helpful for sure.

I wonder if the problem is to do with reassigning `dice`. You probably need to use some React state to trigger a re-render each time `dice` changes. In this case, I would probably also pass the final result to the roll effect, so you can receive it in the listener (rather than as props):

```js
// effects config
const pluginConfig = {
  effects: {
    roll: {
      create: (rollResult) => rollResult,
      duration: 1,
    },
  },
};
```

```js
// example move
function rollDie(G, ctx) {
  G.dieRoll = ctx.random.D6();
  ctx.effects.roll(G.dieRoll);
}
```


```js
// React component
function RolledDice({ G }) {
  // Create component state, using a dice roll stored in the game state as the default value:
  const [dice, setDice] = React.useState(G.dieRoll);

  useEffectListener('roll', async (rollResult) => {
    // Update dice state randomly 10 times:
    for (let i = 0; i < 10; i++) {
      setDice(random(1, 3));
      await sleep(100);
    }
    // Update dice state with final roll:
    setDice(rollResult);
  }, []);

  return <div>{dice}</div>
}
```

**Comment by artt** [comment]
Thanks! Since the `async` thing would wait until the browser is in focus to start playing the animation, I ended up doing this instead which works well (I have more than one dice)

```
	useEffectListener('roll', ({id, roll}) => {
		diceInterval = setInterval(() => {
			setDiceUI(replaceElement(diceUI, id, random(1, 3)))
		}, 100)
	}, []);

	useEffectListener('rollDone', ({id, roll}) => {
		clearInterval(diceInterval)
		setDiceUI(replaceElement(diceUI, catID, roll))
	}, []);
```

**Comment by artt** [comment]
Thanks! Since the `async` thing would wait until the browser is in focus to start playing the animation, I ended up doing this instead which works well (I have more than one dice)

```
useEffectListener('roll', ({id, roll}) => {
	diceInterval = setInterval(() => {
		setDiceUI(replaceElement(diceUI, id, random(1, 3)))
	}, 100)
}, []);

useEffectListener('rollDone', ({id, roll}) => {
	clearInterval(diceInterval)
	setDiceUI(replaceElement(diceUI, id, roll))
}, []);
```
